### ISSUE TITLE
Concentrator won't start

### ISSUE THREAD

**Issue by bjoernbusch** [netceteragroup/rpi-ttn-gateway#5]
I followed the instructions, but I'm getting the following error when starting the container:

```
INFO: [main] Starting the concentrator
ERROR: [main] failed to start the concentrator
/usr/bin/entry.sh: line 93: fg: job has terminated
```

Any hints on what I might be doing wrong?

**Comment by bjoernbusch** [comment]
When I'm installing the software native on my RaspberryPi, the concentrator works fine, so the hardware is working fine.

I'm running on a RaspberryPi3 with HypriotOS v1.4. Any hint would be highly appreciated.

**Comment by squix78** [comment]
Which backplane are you using? We are using [Charles' backplane](https://github.com/ch2i/iC880A-Raspberry-PI) which has the reset pin connected to PIN 17 of the RPi. You might have it connected to PIN 25?

**Comment by bjoernbusch** [comment]
I'm using the [simple Gnz from Tindie](https://www.tindie.com/products/gnz/imst-ic880a-lorawan-backplane-kit/), is that the same? How can I manually trigger a reset?

**Comment by marcelstoer** [comment]
The pin re-assignment is the most likely reason for what you're seeing I believe. Could you please try commenting [line 34 of the Dockerfile](https://github.com/netceteragroup/rpi-ttn-gateway/blob/master/Dockerfile#L33) and [build your own image](https://github.com/netceteragroup/rpi-ttn-gateway/blob/master/README.md#optional-building-the-image-yourself) (either on macOS or the Pi)?

**Comment by bjoernbusch** [comment]
YES! That looks much better!! That seems to solve the issue!

Now I just have one last question about the MAC that needs to be supplied, how do you format that? When I run it native, I get B827EBFFFEA10C04 and I don't seem to get FFFE when running the docker image?

**Comment by marcelstoer** [comment]
> That seems to solve the issue!

Great, good to hear!

Just hours before you raised this issue we had been discussing options for making that pin assignment configureable (Dockerfile env config, multiple Dockerfiles in subfolders, custom base image with extensions, etc.). I'm positive we'll make "that", which ever way it's going to be, available sooner rather than later.

I'm not sure about your MAC address question, though. The address on the host OS (Hypriot) is the same as in the Docker container:
```
$ cat /sys/class/net/eth0/address
b8:27:eb:97:73:e2
$ docker run -it --privileged --net=host --restart=always netceteragroup/rpi-ttn-gateway /bin/bash
root@black-pearl:/opt/ttn-gateway/bin# cat /sys/class/net/eth0/address
b8:27:eb:97:73:e2
```
However, if by running 'native' you mean running the `install.sh` from TTN ZH GitHub repo then https://github.com/ttn-zh/ic880a-gateway/blob/master/install.sh#L47 is probably what you're looking for.
If I'm not mistaken `gateway_ID` in `local_conf.json` simply has to be a unique 8 byte number - the MAC address is as good as any and just so happens to be 64 bits.

**Comment by bjoernbusch** [comment]
ok, yes, this is what I mean. Is there a specific reason that ttn-zh injects the FFFE and you don't?

Anyways, after correcting several typos on my end, I realized that I can just supply the gateway_ID in that format to the container and it works then as I want it to.

Thanks for the help!!

**Comment by marcelstoer** [comment]
> Is there a specific reason that ttn-zh injects the FFFE and you don't?

Now we do 😉  Sorry my previous comment

> the MAC address is as good as any and just so happens to be 64 bits.

was of course wrong. The Pi MAC address is 48 bits, not 64 bits. I added a note about that to the README (→ `GATEWAY_EUI`).

**Comment by bjoernbusch** [comment]
Awesome! Thanks for the clarification!
